// <auto-generated />
using System;
using ChemWatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChemWatch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322135626_AddImportReferenceModels")]
    partial class AddImportReferenceModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChemWatch.Models.InventoryLot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedValue")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("assigned_value");

                    b.Property<string>("CertificateOfAnalysis")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("certificate_of_analysis");

                    b.Property<string>("CertifyingBody")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("certifying_body");

                    b.Property<DateTime>("CheckedInAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<Guid>("CheckedInBy")
                        .HasColumnType("uuid")
                        .HasColumnName("checked_in_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expiry_date");

                    b.Property<int>("ExtensionCount")
                        .HasColumnType("integer")
                        .HasColumnName("extension_count");

                    b.Property<DateTime?>("FirstInspectDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("first_inspect_date");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uuid")
                        .HasColumnName("lab_id");

                    b.Property<DateTime?>("LastMonitorDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_monitor_date");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lot_number");

                    b.Property<string>("ManualSourceReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("manual_source_reason");

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("manufacture_date");

                    b.Property<DateTime?>("NextMonitorDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_monitor_date");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("open_date");

                    b.Property<string>("PeroxideStatus")
                        .HasColumnType("text")
                        .HasColumnName("peroxide_status");

                    b.Property<Guid?>("PurchaseRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<Guid?>("PurchaseRequestItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_item_id");

                    b.Property<string>("QrCodeData")
                        .HasColumnType("jsonb")
                        .HasColumnName("qr_code_data");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("quantity_received");

                    b.Property<decimal>("QuantityRemaining")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("quantity_remaining");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageSublocation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_sublocation");

                    b.Property<string>("Uncertainty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("uncertainty");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_inventory_lots");

                    b.HasIndex("CheckedInBy")
                        .HasDatabaseName("ix_inventory_lots_checked_in_by");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("ix_inventory_lots_expiry_date");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_inventory_lots_item_id");

                    b.HasIndex("LabId")
                        .HasDatabaseName("ix_inventory_lots_lab_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_inventory_lots_location_id");

                    b.HasIndex("LotNumber")
                        .HasDatabaseName("ix_inventory_lots_lot_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_inventory_lots_status");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_inventory_lots_vendor_id");

                    b.HasIndex("ItemId", "LabId")
                        .HasDatabaseName("ix_inventory_lots_item_id_lab_id");

                    b.ToTable("inventory_lots", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowsCheckout")
                        .HasColumnType("boolean")
                        .HasColumnName("allows_checkout");

                    b.Property<string>("CasNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("cas_no");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid?>("DefaultVendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("default_vendor_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsOrderable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_orderable");

                    b.Property<bool>("IsRegulatoryRelated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_regulatory_related");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("item_name");

                    b.Property<string>("ItemShortName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("item_short_name");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("integer")
                        .HasColumnName("lead_time_days");

                    b.Property<string>("PartNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("part_no");

                    b.Property<string>("PeroxideClass")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("peroxide_class");

                    b.Property<decimal?>("ReferencePrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("reference_price");

                    b.Property<bool>("RequiresCheckin")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_checkin");

                    b.Property<bool>("RequiresPeroxideMonitoring")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_peroxide_monitoring");

                    b.Property<string>("Size")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("size");

                    b.Property<string>("StorageConditions")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("storage_conditions");

                    b.Property<bool>("TracksExpiry")
                        .HasColumnType("boolean")
                        .HasColumnName("tracks_expiry");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_items_category_id");

                    b.HasIndex("DefaultVendorId")
                        .HasDatabaseName("ix_items_default_vendor_id");

                    b.ToTable("items", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000001"),
                            AllowsCheckout = true,
                            CasNo = "67-64-1",
                            CategoryId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DefaultVendorId = new Guid("e0000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsOrderable = true,
                            IsRegulatoryRelated = false,
                            ItemName = "Acetone",
                            ItemShortName = "Acetone",
                            LeadTimeDays = 7,
                            PartNo = "179124",
                            ReferencePrice = 45.00m,
                            RequiresCheckin = true,
                            RequiresPeroxideMonitoring = false,
                            Size = "2.5 L",
                            StorageConditions = "Flammable cabinet",
                            TracksExpiry = true,
                            Type = "Solvent",
                            Unit = "L"
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000002"),
                            AllowsCheckout = true,
                            CasNo = "109-99-9",
                            CategoryId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DefaultVendorId = new Guid("e0000000-0000-0000-0000-000000000001"),
                            IsActive = true,
                            IsOrderable = true,
                            IsRegulatoryRelated = true,
                            ItemName = "Tetrahydrofuran (THF)",
                            ItemShortName = "THF",
                            LeadTimeDays = 10,
                            PartNo = "186562",
                            PeroxideClass = "B",
                            ReferencePrice = 62.50m,
                            RequiresCheckin = true,
                            RequiresPeroxideMonitoring = true,
                            Size = "1 L",
                            StorageConditions = "Flammable cabinet, away from light",
                            TracksExpiry = true,
                            Type = "Solvent",
                            Unit = "L"
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000003"),
                            AllowsCheckout = true,
                            CasNo = "7647-01-0",
                            CategoryId = new Guid("d0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DefaultVendorId = new Guid("e0000000-0000-0000-0000-000000000003"),
                            IsActive = true,
                            IsOrderable = true,
                            IsRegulatoryRelated = true,
                            ItemName = "Hydrochloric Acid 37%",
                            ItemShortName = "HCl 37%",
                            LeadTimeDays = 7,
                            PartNo = "320331",
                            ReferencePrice = 35.00m,
                            RequiresCheckin = true,
                            RequiresPeroxideMonitoring = false,
                            Size = "500 mL",
                            StorageConditions = "Corrosives cabinet",
                            TracksExpiry = true,
                            Type = "Acid",
                            Unit = "mL"
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000004"),
                            AllowsCheckout = false,
                            CategoryId = new Guid("d0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DefaultVendorId = new Guid("e0000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsOrderable = true,
                            IsRegulatoryRelated = false,
                            ItemName = "Nitrogen Gas (N2)",
                            ItemShortName = "N2",
                            LeadTimeDays = 3,
                            PartNo = "NI-UHP-K",
                            ReferencePrice = 120.00m,
                            RequiresCheckin = false,
                            RequiresPeroxideMonitoring = false,
                            Size = "K-size cylinder",
                            TracksExpiry = false,
                            Type = "Compressed Gas",
                            Unit = "ea"
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000005"),
                            AllowsCheckout = false,
                            CategoryId = new Guid("d0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            DefaultVendorId = new Guid("e0000000-0000-0000-0000-000000000002"),
                            IsActive = true,
                            IsOrderable = true,
                            IsRegulatoryRelated = false,
                            ItemName = "Nitrile Gloves (Medium)",
                            ItemShortName = "Gloves M",
                            LeadTimeDays = 5,
                            PartNo = "NIT-M-100",
                            ReferencePrice = 18.00m,
                            RequiresCheckin = false,
                            RequiresPeroxideMonitoring = false,
                            Size = "Box of 100",
                            TracksExpiry = false,
                            Type = "PPE",
                            Unit = "box"
                        },
                        new
                        {
                            Id = new Guid("f0000000-0000-0000-0000-000000000006"),
                            AllowsCheckout = true,
                            CategoryId = new Guid("d0000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            IsOrderable = false,
                            IsRegulatoryRelated = true,
                            ItemName = "USP Acetaminophen Reference Standard",
                            ItemShortName = "USP Acetaminophen",
                            PartNo = "1003009",
                            RequiresCheckin = true,
                            RequiresPeroxideMonitoring = false,
                            Size = "200 mg",
                            TracksExpiry = true,
                            Type = "Reference Standard",
                            Unit = "mg"
                        });
                });

            modelBuilder.Entity("ChemWatch.Models.ItemCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_item_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_item_categories_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_item_categories_name");

                    b.ToTable("item_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000001"),
                            Code = "CHEM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laboratory chemicals, solvents, acids, bases, reagents",
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Chemical & Reagent"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000002"),
                            Code = "GAS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Laboratory gases (nitrogen, argon, etc.)",
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Gas"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000003"),
                            Code = "MAT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lab consumables, filters, glassware, PPE",
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Material & Consumable"
                        },
                        new
                        {
                            Id = new Guid("d0000000-0000-0000-0000-000000000004"),
                            Code = "STD",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Certified reference standards (USP, NIST, etc.)",
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Verify STD"
                        });
                });

            modelBuilder.Entity("ChemWatch.Models.ItemLabSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsStocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_stocked");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uuid")
                        .HasColumnName("lab_id");

                    b.Property<decimal?>("MinStock")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("min_stock");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("ReorderQuantity")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("reorder_quantity");

                    b.Property<string>("StorageSublocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("storage_sublocation");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_item_lab_settings");

                    b.HasIndex("LabId")
                        .HasDatabaseName("ix_item_lab_settings_lab_id");

                    b.HasIndex("ItemId", "LabId")
                        .IsUnique()
                        .HasDatabaseName("ix_item_lab_settings_item_id_lab_id");

                    b.ToTable("item_lab_settings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsStocked = true,
                            ItemId = new Guid("f0000000-0000-0000-0000-000000000001"),
                            LabId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            MinStock = 3.0m,
                            ReorderQuantity = 5.0m,
                            StorageSublocation = "Cabinet A2"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsStocked = true,
                            ItemId = new Guid("f0000000-0000-0000-0000-000000000001"),
                            LabId = new Guid("c0000000-0000-0000-0000-000000000007"),
                            MinStock = 2.0m,
                            ReorderQuantity = 4.0m,
                            StorageSublocation = "Shelf B1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsStocked = true,
                            ItemId = new Guid("f0000000-0000-0000-0000-000000000002"),
                            LabId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            MinStock = 2.0m,
                            ReorderQuantity = 3.0m,
                            StorageSublocation = "Flammable Cabinet 1"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsStocked = true,
                            ItemId = new Guid("f0000000-0000-0000-0000-000000000003"),
                            LabId = new Guid("c0000000-0000-0000-0000-00000000000f"),
                            MinStock = 5.0m,
                            ReorderQuantity = 10.0m,
                            StorageSublocation = "Corrosives Cabinet"
                        });
                });

            modelBuilder.Entity("ChemWatch.Models.Lab", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_labs");

                    b.HasIndex("LocationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_labs_location_id_name");

                    b.ToTable("labs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Code = "PO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Name = "PO Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000002"),
                            Code = "EOU",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Name = "EOU Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000003"),
                            Code = "PG",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Name = "PG Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000004"),
                            Code = "POL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Name = "POL Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000005"),
                            Code = "SE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Name = "SE Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000006"),
                            Code = "AIE-SH",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Name = "Shared"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000007"),
                            Code = "EBSM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Name = "EBSM Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000008"),
                            Code = "PS",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Name = "PS Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000009"),
                            Code = "LATEX",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Name = "Latex Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-00000000000a"),
                            Code = "PU",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Name = "PU Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-00000000000b"),
                            Code = "FM",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Name = "FM Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-00000000000c"),
                            Code = "EFF",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Name = "EFF Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-00000000000d"),
                            Code = "PE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Name = "PE Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-00000000000e"),
                            Code = "MTP-SH",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Name = "Shared"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-00000000000f"),
                            Code = "CT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Name = "CT Lab"
                        },
                        new
                        {
                            Id = new Guid("c0000000-0000-0000-0000-000000000010"),
                            Code = "ATC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            LocationId = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Name = "ATC Lab"
                        });
                });

            modelBuilder.Entity("ChemWatch.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_code");

                    b.ToTable("locations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Code = "AIE",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "AIE"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            Code = "MTP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "MTP"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            Code = "CT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "CT"
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            Code = "ATC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "ATC"
                        });
                });

            modelBuilder.Entity("ChemWatch.Models.PeroxideConfigRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("DisposeAfterOpeningMonths")
                        .HasColumnType("integer")
                        .HasColumnName("dispose_after_opening_months");

                    b.Property<int?>("DisposeAfterReceiptMonths")
                        .HasColumnType("integer")
                        .HasColumnName("dispose_after_receipt_months");

                    b.Property<string>("PeroxideClass")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("peroxide_class");

                    b.Property<bool>("TestBeforeUse")
                        .HasColumnType("boolean")
                        .HasColumnName("test_before_use");

                    b.Property<int?>("TestIntervalMonths")
                        .HasColumnType("integer")
                        .HasColumnName("test_interval_months");

                    b.HasKey("Id")
                        .HasName("pk_peroxide_config_rules");

                    b.HasIndex("PeroxideClass")
                        .IsUnique()
                        .HasDatabaseName("ix_peroxide_config_rules_peroxide_class");

                    b.ToTable("peroxide_config_rules", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.PeroxideTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("classification");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventoryLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_lot_id");

                    b.Property<DateTime?>("NextMonitorDue")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("next_monitor_due");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<decimal?>("PpmResult")
                        .HasColumnType("numeric")
                        .HasColumnName("ppm_result");

                    b.Property<string>("ResultText")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result_text");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_type");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("test_date");

                    b.Property<string>("TestMethod")
                        .HasColumnType("text")
                        .HasColumnName("test_method");

                    b.Property<Guid>("TestedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("tested_by_user_id");

                    b.Property<string>("VisualObservations")
                        .HasColumnType("text")
                        .HasColumnName("visual_observations");

                    b.HasKey("Id")
                        .HasName("pk_peroxide_tests");

                    b.HasIndex("InventoryLotId")
                        .HasDatabaseName("ix_peroxide_tests_inventory_lot_id");

                    b.HasIndex("TestDate")
                        .HasDatabaseName("ix_peroxide_tests_test_date");

                    b.HasIndex("TestedByUserId")
                        .HasDatabaseName("ix_peroxide_tests_tested_by_user_id");

                    b.ToTable("peroxide_tests", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.PoReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("LabId")
                        .HasColumnType("uuid")
                        .HasColumnName("lab_id");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("po_number");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_po_references");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_po_references_category_id");

                    b.HasIndex("LabId")
                        .HasDatabaseName("ix_po_references_lab_id");

                    b.HasIndex("PoNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_po_references_po_number");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_po_references_vendor_id");

                    b.ToTable("po_references", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.PurchaseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalNotes")
                        .HasColumnType("text")
                        .HasColumnName("approval_notes");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LabId")
                        .HasColumnType("uuid")
                        .HasColumnName("lab_id");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_modified_at");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("last_modified_by");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<string>("OrderNotes")
                        .HasColumnType("text")
                        .HasColumnName("order_notes");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("po_number");

                    b.Property<string>("RejectedReason")
                        .HasColumnType("text")
                        .HasColumnName("rejected_reason");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_purchase_requests");

                    b.HasIndex("ApprovedBy")
                        .HasDatabaseName("ix_purchase_requests_approved_by");

                    b.HasIndex("LabId")
                        .HasDatabaseName("ix_purchase_requests_lab_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_purchase_requests_location_id");

                    b.HasIndex("PoNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_requests_po_number");

                    b.HasIndex("RequestedBy")
                        .HasDatabaseName("ix_purchase_requests_requested_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_purchase_requests_status");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("ix_purchase_requests_submitted_at");

                    b.ToTable("purchase_requests", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.PurchaseRequestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("LineItemNotes")
                        .HasColumnType("text")
                        .HasColumnName("line_item_notes");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<decimal>("QuantityOrdered")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("quantity_ordered");

                    b.Property<decimal>("QuantityReceived")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("quantity_received");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_purchase_request_items");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_purchase_request_items_item_id");

                    b.HasIndex("PurchaseRequestId")
                        .HasDatabaseName("ix_purchase_request_items_purchase_request_id");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_purchase_request_items_vendor_id");

                    b.ToTable("purchase_request_items", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.PurchaseRequestItemRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<string>("FieldName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("field_name");

                    b.Property<string>("NewValue")
                        .HasColumnType("text")
                        .HasColumnName("new_value");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OldValue")
                        .HasColumnType("text")
                        .HasColumnName("old_value");

                    b.Property<Guid>("PurchaseRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<Guid?>("PurchaseRequestItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_item_id");

                    b.Property<DateTime>("RevisedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revised_at");

                    b.Property<Guid>("RevisedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("revised_by");

                    b.HasKey("Id")
                        .HasName("pk_purchase_request_item_revisions");

                    b.HasIndex("PurchaseRequestId")
                        .HasDatabaseName("ix_purchase_request_item_revisions_purchase_request_id");

                    b.HasIndex("PurchaseRequestItemId")
                        .HasDatabaseName("ix_purchase_request_item_revisions_purchase_request_item_id");

                    b.HasIndex("RevisedBy")
                        .HasDatabaseName("ix_purchase_request_item_revisions_revised_by");

                    b.ToTable("purchase_request_item_revisions", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access across all locations and labs",
                            DisplayName = "Admin",
                            IsActive = true,
                            Name = "admin"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manages operations for assigned locations. Approves orders, manages inventory.",
                            DisplayName = "Focal Point",
                            IsActive = true,
                            Name = "focal_point"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Day-to-day operational user. Creates orders, checks out chemicals.",
                            DisplayName = "User",
                            IsActive = true,
                            Name = "user"
                        });
                });

            modelBuilder.Entity("ChemWatch.Models.ShelfLifeExtension", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorizedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorized_by_user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ExtensionDays")
                        .HasColumnType("integer")
                        .HasColumnName("extension_days");

                    b.Property<int>("ExtensionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("extension_number");

                    b.Property<Guid>("InventoryLotId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_lot_id");

                    b.Property<int>("NewDaysToExpiry")
                        .HasColumnType("integer")
                        .HasColumnName("new_days_to_expiry");

                    b.Property<DateTime>("NewExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("new_expiry_date");

                    b.Property<int?>("PreviousDaysToExpiry")
                        .HasColumnType("integer")
                        .HasColumnName("previous_days_to_expiry");

                    b.Property<DateTime?>("PreviousExpiryDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("previous_expiry_date");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("TestDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("test_date");

                    b.Property<string>("TestPerformed")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("test_performed");

                    b.Property<string>("TestResult")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("test_result");

                    b.HasKey("Id")
                        .HasName("pk_shelf_life_extensions");

                    b.HasIndex("AuthorizedByUserId")
                        .HasDatabaseName("ix_shelf_life_extensions_authorized_by_user_id");

                    b.HasIndex("InventoryLotId")
                        .HasDatabaseName("ix_shelf_life_extensions_inventory_lot_id");

                    b.ToTable("shelf_life_extensions", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid?>("LabId")
                        .HasColumnType("uuid")
                        .HasColumnName("lab_id");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid?>("LotId")
                        .HasColumnType("uuid")
                        .HasColumnName("lot_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PurchaseRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("purchase_request_id");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(12,3)")
                        .HasColumnName("quantity");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("transaction_type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_stock_transactions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_stock_transactions_created_at");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_stock_transactions_item_id");

                    b.HasIndex("LabId")
                        .HasDatabaseName("ix_stock_transactions_lab_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_stock_transactions_location_id");

                    b.HasIndex("LotId")
                        .HasDatabaseName("ix_stock_transactions_lot_id");

                    b.HasIndex("PurchaseRequestId")
                        .HasDatabaseName("ix_stock_transactions_purchase_request_id");

                    b.HasIndex("TransactionType")
                        .HasDatabaseName("ix_stock_transactions_transaction_type");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_stock_transactions_user_id");

                    b.ToTable("stock_transactions", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.TestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_test_items");

                    b.ToTable("test_items", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LocationScopeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("location_scope_type");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@chemwatch.local",
                            FullName = "System Admin",
                            IsActive = true,
                            LocationScopeType = "all",
                            PasswordHash = "$2a$11$KXpGgVx0kUsaH5SzYFnBxu3pBXYf3MkGz8S1G0gKjHc5xV3uMCPyG",
                            RoleId = new Guid("a0000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("ChemWatch.Models.UserLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_locations");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_user_locations_location_id");

                    b.HasIndex("UserId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_locations_user_id_location_id");

                    b.ToTable("user_locations", (string)null);
                });

            modelBuilder.Entity("ChemWatch.Models.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vendors_name");

                    b.ToTable("vendors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000001"),
                            Code = "SIGMA",
                            ContactEmail = "orders@sigma.example.com",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Sigma-Aldrich",
                            Website = "https://www.sigmaaldrich.com"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000002"),
                            Code = "FISHER",
                            ContactEmail = "orders@fisher.example.com",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Fisher Scientific",
                            Website = "https://www.fishersci.com"
                        },
                        new
                        {
                            Id = new Guid("e0000000-0000-0000-0000-000000000003"),
                            Code = "MERCK",
                            ContactEmail = "orders@merck.example.com",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Merck",
                            Website = "https://www.merck.com"
                        });
                });

            modelBuilder.Entity("ChemWatch.Models.InventoryLot", b =>
                {
                    b.HasOne("ChemWatch.Models.User", "CheckedInByUser")
                        .WithMany()
                        .HasForeignKey("CheckedInBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_lots_users_checked_in_by");

                    b.HasOne("ChemWatch.Models.Item", "Item")
                        .WithMany("InventoryLots")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_lots_items_item_id");

                    b.HasOne("ChemWatch.Models.Lab", "Lab")
                        .WithMany("InventoryLots")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_lots_labs_lab_id");

                    b.HasOne("ChemWatch.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_lots_locations_location_id");

                    b.HasOne("ChemWatch.Models.Vendor", "Vendor")
                        .WithMany("InventoryLots")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_inventory_lots_vendors_vendor_id");

                    b.Navigation("CheckedInByUser");

                    b.Navigation("Item");

                    b.Navigation("Lab");

                    b.Navigation("Location");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ChemWatch.Models.Item", b =>
                {
                    b.HasOne("ChemWatch.Models.ItemCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_items_item_categories_category_id");

                    b.HasOne("ChemWatch.Models.Vendor", "DefaultVendor")
                        .WithMany("Items")
                        .HasForeignKey("DefaultVendorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_items_vendors_default_vendor_id");

                    b.Navigation("Category");

                    b.Navigation("DefaultVendor");
                });

            modelBuilder.Entity("ChemWatch.Models.ItemLabSetting", b =>
                {
                    b.HasOne("ChemWatch.Models.Item", "Item")
                        .WithMany("ItemLabSettings")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_lab_settings_items_item_id");

                    b.HasOne("ChemWatch.Models.Lab", "Lab")
                        .WithMany("ItemLabSettings")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_lab_settings_labs_lab_id");

                    b.Navigation("Item");

                    b.Navigation("Lab");
                });

            modelBuilder.Entity("ChemWatch.Models.Lab", b =>
                {
                    b.HasOne("ChemWatch.Models.Location", "Location")
                        .WithMany("Labs")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_labs_locations_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("ChemWatch.Models.PeroxideTest", b =>
                {
                    b.HasOne("ChemWatch.Models.InventoryLot", "InventoryLot")
                        .WithMany("PeroxideTests")
                        .HasForeignKey("InventoryLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_peroxide_tests_inventory_lots_inventory_lot_id");

                    b.HasOne("ChemWatch.Models.User", "TestedByUser")
                        .WithMany()
                        .HasForeignKey("TestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_peroxide_tests_users_tested_by_user_id");

                    b.Navigation("InventoryLot");

                    b.Navigation("TestedByUser");
                });

            modelBuilder.Entity("ChemWatch.Models.PoReference", b =>
                {
                    b.HasOne("ChemWatch.Models.ItemCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_po_references_item_categories_category_id");

                    b.HasOne("ChemWatch.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_po_references_labs_lab_id");

                    b.HasOne("ChemWatch.Models.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_po_references_vendors_vendor_id");

                    b.Navigation("Category");

                    b.Navigation("Lab");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ChemWatch.Models.PurchaseRequest", b =>
                {
                    b.HasOne("ChemWatch.Models.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_purchase_requests_users_approved_by");

                    b.HasOne("ChemWatch.Models.Lab", "Lab")
                        .WithMany()
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_requests_labs_lab_id");

                    b.HasOne("ChemWatch.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_requests_locations_location_id");

                    b.HasOne("ChemWatch.Models.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_requests_users_requested_by");

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Lab");

                    b.Navigation("Location");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("ChemWatch.Models.PurchaseRequestItem", b =>
                {
                    b.HasOne("ChemWatch.Models.Item", "Item")
                        .WithMany("PurchaseRequestItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_request_items_items_item_id");

                    b.HasOne("ChemWatch.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_request_items_purchase_requests_purchase_request_id");

                    b.HasOne("ChemWatch.Models.Vendor", "Vendor")
                        .WithMany("PurchaseRequestItems")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_purchase_request_items_vendors_vendor_id");

                    b.Navigation("Item");

                    b.Navigation("PurchaseRequest");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ChemWatch.Models.PurchaseRequestItemRevision", b =>
                {
                    b.HasOne("ChemWatch.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany("Revisions")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_request_item_revisions_purchase_requests_purchase_");

                    b.HasOne("ChemWatch.Models.PurchaseRequestItem", "PurchaseRequestItem")
                        .WithMany("Revisions")
                        .HasForeignKey("PurchaseRequestItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_purchase_request_item_revisions_purchase_request_items_purc");

                    b.HasOne("ChemWatch.Models.User", "RevisedByUser")
                        .WithMany()
                        .HasForeignKey("RevisedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_purchase_request_item_revisions_users_revised_by");

                    b.Navigation("PurchaseRequest");

                    b.Navigation("PurchaseRequestItem");

                    b.Navigation("RevisedByUser");
                });

            modelBuilder.Entity("ChemWatch.Models.ShelfLifeExtension", b =>
                {
                    b.HasOne("ChemWatch.Models.User", "AuthorizedByUser")
                        .WithMany()
                        .HasForeignKey("AuthorizedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shelf_life_extensions_users_authorized_by_user_id");

                    b.HasOne("ChemWatch.Models.InventoryLot", "InventoryLot")
                        .WithMany("ShelfLifeExtensions")
                        .HasForeignKey("InventoryLotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_shelf_life_extensions_inventory_lots_inventory_lot_id");

                    b.Navigation("AuthorizedByUser");

                    b.Navigation("InventoryLot");
                });

            modelBuilder.Entity("ChemWatch.Models.StockTransaction", b =>
                {
                    b.HasOne("ChemWatch.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_transactions_items_item_id");

                    b.HasOne("ChemWatch.Models.Lab", "Lab")
                        .WithMany("StockTransactions")
                        .HasForeignKey("LabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_transactions_labs_lab_id");

                    b.HasOne("ChemWatch.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_transactions_locations_location_id");

                    b.HasOne("ChemWatch.Models.InventoryLot", "InventoryLot")
                        .WithMany("StockTransactions")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_transactions_inventory_lots_lot_id");

                    b.HasOne("ChemWatch.Models.PurchaseRequest", "PurchaseRequest")
                        .WithMany("StockTransactions")
                        .HasForeignKey("PurchaseRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_transactions_purchase_requests_purchase_request_id");

                    b.HasOne("ChemWatch.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_transactions_users_user_id");

                    b.Navigation("InventoryLot");

                    b.Navigation("Item");

                    b.Navigation("Lab");

                    b.Navigation("Location");

                    b.Navigation("PurchaseRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChemWatch.Models.User", b =>
                {
                    b.HasOne("ChemWatch.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ChemWatch.Models.UserLocation", b =>
                {
                    b.HasOne("ChemWatch.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_locations_locations_location_id");

                    b.HasOne("ChemWatch.Models.User", "User")
                        .WithMany("UserLocations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_locations_users_user_id");

                    b.Navigation("Location");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChemWatch.Models.InventoryLot", b =>
                {
                    b.Navigation("PeroxideTests");

                    b.Navigation("ShelfLifeExtensions");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("ChemWatch.Models.Item", b =>
                {
                    b.Navigation("InventoryLots");

                    b.Navigation("ItemLabSettings");

                    b.Navigation("PurchaseRequestItems");
                });

            modelBuilder.Entity("ChemWatch.Models.ItemCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ChemWatch.Models.Lab", b =>
                {
                    b.Navigation("InventoryLots");

                    b.Navigation("ItemLabSettings");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("ChemWatch.Models.Location", b =>
                {
                    b.Navigation("Labs");
                });

            modelBuilder.Entity("ChemWatch.Models.PurchaseRequest", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Revisions");

                    b.Navigation("StockTransactions");
                });

            modelBuilder.Entity("ChemWatch.Models.PurchaseRequestItem", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("ChemWatch.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ChemWatch.Models.User", b =>
                {
                    b.Navigation("UserLocations");
                });

            modelBuilder.Entity("ChemWatch.Models.Vendor", b =>
                {
                    b.Navigation("InventoryLots");

                    b.Navigation("Items");

                    b.Navigation("PurchaseRequestItems");
                });
#pragma warning restore 612, 618
        }
    }
}
